server:
  port: 6001

spring:
  application:
    name: RESTAURANT-SERVICE

eureka:
  client:
    fetch-with-eureka: true
    fetch-registry: true
    servivce-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost