server:
  port: 8000

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: RESTAURANT-SERVICE
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurants/**
          filters:
            - name: CircuitBreaker
              args:
                name: RESTAURANT-SERVICE
                fallbackuri: forward:/restaurantServiceFallbackController
        - id: FOOD-ITEM-SERVICE
          uri: lb://FOOD-ITEM-SERVICE
          predicates:
            - Path=/foodItems/**
          filters:
            - name: CircuitBreaker
              args:
                name: FOOD-ITEM-SERVICE
                fallbackuri: forward:/foodItemServiceFallbackController


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 6000
          strategy: SEMAPHORE


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream